import type { Metadata } from 'next'
import { Inter, Space_Mono } from 'next/font/google'
import '../styles/globals.css'
import Footer from '../layout/Footer'
import ThemeInitializer from '../components/ThemeInitializer'
import Header from '@/layout/Header'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})

const spaceMono = Space_Mono({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-space-mono',
})

export const metadata: Metadata = {
  title: 'Next.js Shop',
  description: 'Generated by create next app',
  icons: {
    icon: '/icons/shop.svg',
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${spaceMono.variable} antialiased`}>
        <Header />
        <main className="mb-5 mt-[3rem] p-4">
          <ThemeInitializer />
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
